# Generated by Django 6.0.7 on 2026-07-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alatpay_subaccount_id', models.CharField(blank=True, max_length=100, null=True)),
                ('alatpay_subaccount_ref', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
